version: '3.3'
services:
  web:
    image: node:latest
    ports:
      - '5000:5000'
    depends_on:
      - mariadb
    volumes:
      - ./:/app
    working_dir: /app
    command: npm start

  mariadb:
    image: mariadb:latest
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_DATABASE: twitter
      MYSQL_USER: twitter
      MYSQL_PASSWORD: twitsecret
