version: '2.1'
services:
  web:
    image: node:latest
    ports:
      - '5000:5000'
    depends_on:
      mariadb:
        condition: service_healthy

    volumes:
      - ./:/app
    working_dir: /app
    command: npm start

  mariadb:
    image: mariadb:latest
    ports:
      - '3306:3306'
    healthcheck:
      test: mysqladmin -utwitter -ptwitsecret ping
      interval: 2s
      timeout: 5s
      retries: 30
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_DATABASE: twitter
      MYSQL_USER: twitter
      MYSQL_PASSWORD: twitsecret
